application: zardoztestzone
version: 1
runtime: python
api_version: 1

handlers: 
- url: /static
  static_dir: static

- url: /js
  static_dir: js  
  
- url: /.*
  script: master.py
  
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*UnitTests\\*.*